[build]
  publish = "Build"
  command = "npm run build" # Dacă folosești un script de build specific

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline';"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"